// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";

function AddPostForm(Props) {
  Props.closeModal;
  React.useState((function () {
          return "";
        }));
  React.useState((function () {
          return "";
        }));
  React.useState((function () {
          return false;
        }));
  var match = React.useState((function () {
          return "https://res.cloudinary.com/bracket-factory/image/upload/v1563567377/reason_blog_hong_kong.jpg";
        }));
  var setCoverImage = match[1];
  return React.createElement("input", {
              onChange: (function (e) {
                  return Curry._1(setCoverImage, e.target.value);
                })
            });
}

var make = AddPostForm;

export {
  make ,
  
}
/* react Not a pure module */
