// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";

var logo = require("../img/logo.svg");

function Header(Props) {
  Props.openModal;
  Props.isModalOpened;
  return React.createElement("header", {
              className: "flex mb-4 sticky top-0"
            });
}

var make = Header;

export {
  logo ,
  make ,
  
}
/* logo Not a pure module */
