// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as ApolloLinks from "reason-apollo/src/ApolloLinks.bs.js";
import * as ApolloLink from "apollo-link";
import * as ReasonApollo from "reason-apollo/src/ReasonApollo.bs.js";
import * as ApolloUtilities from "apollo-utilities";
import * as ApolloInMemoryCache from "reason-apollo/src/ApolloInMemoryCache.bs.js";

function makeApollo(param) {
  var inMemoryCache = ApolloInMemoryCache.createInMemoryCache(undefined, undefined, /* () */0);
  var webSocketLink = ApolloLinks.webSocketLink("ws://localhost:8080/v1/graphql", true, undefined, /* () */0);
  var httpLink = ApolloLinks.createHttpLink("ws://localhost:8080/v1/graphql", undefined, undefined, undefined, undefined, undefined, /* () */0);
  var link = ApolloLink.split((function (operation) {
          var operationDefinition = ApolloUtilities.getMainDefinition(operation.query);
          if (operationDefinition.kind === "OperationDefinition") {
            return operationDefinition.operation === "subscription";
          } else {
            return false;
          }
        }), webSocketLink, httpLink);
  return ReasonApollo.createApolloClient(link, inMemoryCache, undefined, undefined, undefined, undefined, /* () */0);
}

export {
  makeApollo ,
  
}
/* ApolloLinks Not a pure module */
