// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Serviceworker from "./serviceworker";

function register_service_worker(prim) {
  Serviceworker.register();
  return /* () */0;
}

function unregister_service_worker(prim) {
  Serviceworker.unregister();
  return /* () */0;
}

export {
  register_service_worker ,
  unregister_service_worker ,
  
}
/* ./serviceworker Not a pure module */
